columns:
  Item_Identifier: object
  Item_Weight: float64
  Item_Fat_Content: object
  Item_Visibility: float64
  Item_Type: object
  Item_MRP: float64
  Outlet_Identifier: object
  Outlet_Establishment_Year: int64
  Outlet_Size: object
  Outlet_Location_Type: object
  Outlet_Type: object
  Item_Outlet_Sales: float64

numerical_columns:
  - Item_Weight
  - Item_Visibility
  - Item_MRP

nominal_cat_columns:
  - Item_Type
  - Outlet_Type

ordinal_cat_columns:
  - Item_Fat_Content
  - Outlet_Size
  - Outlet_Location_Type

categorical_columns:
  - Item_Type
  - Outlet_Type
  - Item_Fat_Content
  - Outlet_Size
  - Outlet_Location_Type

target_columns: Item_Outlet_Sales

id_columns:
  - Item_Identifier
  - Outlet_Identifier

year_columns: Outlet_Establishment_Year  

domain_value:

  Item_Fat_Content:
   - Low Fat
   - Regular
  Outlet_Size:
   - Small
   - Medium
   - High
  Outlet_Location_Type:
   - Tier 1
   - Tier 2
   - Tier 3

